### ISSUE TITLE
Arch values inconsistent between Node and Debian

### ISSUE THREAD

**Issue by abertranb** [electron-userland/electron-installer-debian#177]
Hi I'm trying to create a debian for 32 bits and I can't, with 64 bits works fine

electron-packager . app --overwrite --asar --platform=linux --arch=x64 --icon=assets/icons/png/1024x1024.png --prune=true --out=release-builds

but with 32 I can't

electron-packager . app --overwrite --asar --platform=linux --arch=x86 --icon=assets/icons/png/1024x1024.png --prune=true --out=release-builds

The output is
```
Unsupported arch=x86 (string); must be a string matching: ia32, x64, armv7l, arm64, mips64el
```
Then we create with ia32 debian raises
```
dpkg: error processing archive app_1.0.14-eva_ia32.deb (--install):
package architecture (ia32) is not of the system (i386)
```
I tryed with i386 but raises the same Unsupported error 
thanks!

**Comment by malept** [comment]
I've moved this issue to `electron-installer-debian` because this is not an Electron Packager issue. [The Packager docs](https://github.com/electron-userland/electron-packager/blob/v13.0.1/docs/api.md#arch) state which arch values are valid. These values are all Node arch values that do not necessarily follow the conventions of other systems.

Meanwhile, `electron-installer-debian` expects `arch` to be a Debian value. _(Side note: `x86` is not a valid Debian arch either, it's `i386`.)_ I think this is a usability bug. Electron Forge has [a function to transform arch values](https://github.com/electron-userland/electron-forge/blob/7abaf7f749800c57fc0c6451121a0698246d5f50/packages/maker/deb/src/MakerDeb.ts#L7-L15) that should be in `electron-installer-debian` instead.

**Comment by fcastilloec** [comment]
I don't think this is really an issue if people actually read the documentation on both projects.
As you have mentioned, if you run `electron-packager` with `ia32` and then use `electron-installer-debian` with `i386` then it should work without a problem.

Having a transform function on projects like Electron Forge makes sense but definitely not here. We could package using many different 32bit architectures (uclinux-i386, solaris-i386, etc.) so we cannot and should not try to read the user's mind of what they want/need if they package it using `ia32`.
What we can do is place something on the README pointing out that the names use by Node are not the same names used in Debian. We already mention how to get a list of all architectures that we could pack for in [options.arch](https://github.com/electron-userland/electron-installer-debian#optionsarch).
For example, my system can package a `ia32` using `ia32` with `-debian`, it also works it `i386` and many of the other 32bit desktop archs. Others will throw errors when using `ia32` as the original poster mentioned.

**Comment by malept** [comment]
For reference, `electron-installer-flatpak` already has this behavior (via [`flatpak-bundler`](https://github.com/endlessm/flatpak-bundler/blob/74c4eaa977483da62799a5f0a57e46969dda5202/index.js#L29-L35)).

**Comment by abertranb** [comment]
Great thanks!

Then I run
```
electron-packager . myapp --overwrite --asar --platform=linux --arch=ia32 --icon=assets/icons/png/1024x1024.png --prune=true --out=release-builds
electron-installer-debian --src release-builds/myapp-linux-ia32/ --arch i386 --config debian.json
```

Thanks!!!
