### ISSUE TITLE
incorrect electron-packager command

### ISSUE THREAD

**Issue by Suresh-Kumar-A** [electron-userland/electron-installer-debian#267]
**What version of `electron-installer-debian` are you using?**
3.1.0
**What version of `node` and `npm` are you using?**
node version is 12.21.0  and npm version is 7.20.6 
**What operating system are you using?**
ubuntu 21.04
**Can you compile the [example app](https://github.com/electron-userland/electron-installer-debian/tree/master/example) successfully?**
not tried it
**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/electron-userland/electron-installer-debian.git
$ cd electron-installer-debian/example
$ DEBUG='electron-installer-debian' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-debian`.**

**What did you expect to happen?**
successful build of electron deb package when tried to build the sample angular electron package with `electron-installer-debian` command provided in README.md file
**What actually happened?**
got the error electron-packager: command not found
**[Fixed] Solution**
Raised Pull Request #266  with Updated changes in README.md file

**Comment by fcastilloec** [comment]
I can see why you would think this is a problem, but we deliberately left it like that because some people have installed `electron-packager` globally, other people might use `yarn`.
It's understood that you need to run `electron-packager` for this module to work, how you do that is out of the scope of this project. You might even use your own packaging that is compatible and passes that to `electron-installer-debian` without even using `electron-packager`.
